name: Tag Repo (Bump Version)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  tag:
    name: tag
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    continue-on-error: true


    steps:
      - uses: actions/checkout@master

      - name: tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GH_TOKEN}}
