name: Terraform
on:
  push:
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest

    steps:

      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@v2.4.0
        with:
            url: URL_HERE
            namespace: admin
            method: jwt
            role: workshop
            tlsSkipVerify: false
            secrets: |
              terraform/creds/workshop token | TFC_TEAM_TOKEN ;
              gcp/roleset/workshop/key private_key_data | GOOGLE_CREDENTIALS ;
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ steps.secrets.outputs.TFC_TEAM_TOKEN }}
          cli_config_credentials_hostname: 'app.terraform.io'


      - name: Terraform Init
        run: terraform init -input=false
        env:
          TF_WORKSPACE: "dev"
          TF_IN_AUTOMATION: "true"
          GOOGLE_CREDENTIALS: ${{ steps.secrets.outputs.GOOGLE_CREDENTIALS }}

      - name: Terraform Format
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan -input=false
        env:
          TF_WORKSPACE: "dev"
          TF_IN_AUTOMATION: "true"

      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve
        env:
          TF_WORKSPACE: "dev"
          TF_IN_AUTOMATION: "true"